name: "UI TEST"

on: push

jobs:
  accessibility-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Start Storybook in background
        run: npm run storybook --ci --host 0.0.0.0 &

      - name: Wait for Storybook to start
        run: |
          echo "Waiting for Storybook to start..."
          timeout=120
          while ! curl -s http://localhost:6006 > /dev/null; do
            sleep 5
            timeout=$((timeout - 5))
            if [ $timeout -le 0 ]; then
              echo "Timed out waiting for Storybook to start"
              exit 1
            fi
          done
          echo "Storybook is running"

      - name: Run Storybook tests
        run: npm run test-storybook --url http://localhost:6006
        env:
          TARGET_URL: '${{ github.event.deployment_status.target_url }}'

  chromatic:
    needs: accessibility-test
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install dependencies
        # ⚠️ See your package manager's documentation for the correct command to install dependencies in a CI environment.
        run: npm ci
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
